<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    
    <parent>
        <groupId>net.jeebiz</groupId>
        <artifactId>jeebiz-boot-parent</artifactId>
        <version>2.0.x.20260630-SNAPSHOT</version>

    <properties>
        <java.version>17</java.version>
        <maven.compiler.release>${java.version}</maven.compiler.release>
        <maven.version>3.9.16</maven.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
        <relativePath />
    </parent>
     
    <groupId>io.github.easy4j</groupId>
    <artifactId>spring-boot-starter-samples</artifactId>
    <version>2.0.x.20260630-SNAPSHOT</version>

    <packaging>pom</packaging>
    <name>Spring Boot Starter Samples</name>
    <description>Spring Boot Starter Samples</description>

    <modules>

        <module>spring-boot-sample-axis2</module>
        <module>spring-boot-sample-casclient</module>
        <module>spring-boot-sample-cxf</module>
        <module>spring-boot-sample-disruptor</module>
        <module>spring-boot-sample-druid</module>
        <module>spring-boot-sample-ehcache3</module>
        <module>spring-boot-sample-flyway</module>
        <module>spring-boot-sample-hikaricp</module>
        <module>spring-boot-sample-jetbrick</module>
        <module>spring-boot-sample-kaptcha</module>
        <module>spring-boot-sample-log4j2</module>
        <module>spring-boot-sample-pf4j</module>
        <module>spring-boot-sample-rocketmq</module>
        <module>spring-boot-sample-swagger2</module>
        <module>spring-boot-sample-websocket</module>
        <module>spring-boot-sample-sharding-jdbc</module>
        <module>spring-boot-sample-pf4j2</module>
        <module>spring-boot-sample-socketio</module>
    </modules>
    
</project>